In [2]:
import numpy as np

In [3]:
base_data = np.arange(100,200)
print('base_data\n ={}\n'.format(base_data))


base_data
 =[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]



In [5]:
print('base_data[10] ={}\n'.format(base_data[10]))

base_data[10] =110



In [7]:
every_five = np.arange(0,100,5)
print(every_five)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [8]:
print('base_data[every_five] = \n{}\n'.format(base_data[every_five]))


base_data[every_five] = 
[100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180 185
 190 195]



In [10]:
a = np.array([(1,2), (10,20)])
print('a = \n{}\n'.format(a))

a = 
[[ 1  2]
 [10 20]]



In [11]:
base_data[a]

array([[101, 102],
       [110, 120]])

In [13]:
base_data2 = base_data.reshape(10,-1)
print('base_data = np.reshape(base_data, (10,-1)) = \n{}\n'.format(base_data2))

base_data = np.reshape(base_data, (10,-1)) = 
[[100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]]



In [14]:
base_data2[2]

array([120, 121, 122, 123, 124, 125, 126, 127, 128, 129])

In [16]:
base_data2[2,3]

123

In [17]:
base_data2[-1,-1]

199

In [18]:
base_data2[2,:]

array([120, 121, 122, 123, 124, 125, 126, 127, 128, 129])

In [19]:
base_data2[:,3]


array([103, 113, 123, 133, 143, 153, 163, 173, 183, 193])

In [21]:
base_data2[2:5, 2:4]

array([[122, 123],
       [132, 133],
       [142, 143]])

In [28]:
base_data = (np.random.random((5,5))-0.5) *100
print(base_data)

[[ -5.41017433  11.28932911 -39.71086865  11.9510019   23.18117713]
 [  9.15132036  -3.50351798  23.60988194 -29.00823217 -21.75845089]
 [  1.04458429 -27.80240299 -28.92061321  36.98650168  -4.29332219]
 [ 36.41732598  37.05141508  13.88440686 -31.80542452 -17.05327125]
 [ -1.31133792  15.23752395  14.01164599  47.68517082   3.32596819]]


In [30]:
print(np.amin(base_data))

-39.7108686484844


In [31]:
print(np.amax(base_data))

47.68517082369844


In [34]:
print(np.average(base_data))

2.9699854871904563


In [35]:
print(np.sum(base_data))

74.24963717976141


In [36]:
print(np.sin(base_data))

[[ 0.76626702 -0.95716342 -0.90434214 -0.57725964 -0.92837958]
 [ 0.27006217  0.35407549 -0.99885124  0.66976946 -0.23060334]
 [ 0.86471582 -0.45460697  0.60222026 -0.65381099  0.91346907]
 [-0.95852637 -0.60335123  0.96822588 -0.37972404  0.97468504]
 [-0.96652907  0.45327793  0.99213258 -0.53227111 -0.18333269]]


In [39]:
arr = np.arange(1,20)

In [40]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [42]:
arr = arr * arr
print(arr)

[  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324
 361]


In [43]:
arr = arr-arr
print(arr)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [45]:
arr = np.arange(1,20)
arr = arr+arr
print(arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [46]:
arr = arr/arr
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [47]:
arr = np.arange(1,20)

In [48]:
arr = arr+50
print(arr)

[51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [51]:
base_data = np.floor((np.random.random((5,5))-0.5) *100)
print(base_data)

[[ 46.  19.  -3.  45.  35.]
 [-17. -37.  28. -41.  39.]
 [  2.  -4.  32. -48.  41.]
 [ 18.  -8. -28.   8. -23.]
 [ 39.  37. -40. -35. -33.]]


In [52]:
print(base_data.T)

[[ 46. -17.   2.  18.  39.]
 [ 19. -37.  -4.  -8.  37.]
 [ -3.  28.  32. -28. -40.]
 [ 45. -41. -48.   8. -35.]
 [ 35.  39.  41. -23. -33.]]


In [53]:
print(base_data.transpose())

[[ 46. -17.   2.  18.  39.]
 [ 19. -37.  -4.  -8.  37.]
 [ -3.  28.  32. -28. -40.]
 [ 45. -41. -48.   8. -35.]
 [ 35.  39.  41. -23. -33.]]


In [55]:
matrix1 = np.ones((5,5))

In [56]:
print(matrix1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [57]:
minus_one = np.dot(matrix1,-1)

In [60]:
print(minus_one)

[[-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]]


In [61]:
print(np.dot(base_data, minus_one))

[[-142. -142. -142. -142. -142.]
 [  28.   28.   28.   28.   28.]
 [ -23.  -23.  -23.  -23.  -23.]
 [  33.   33.   33.   33.   33.]
 [  32.   32.   32.   32.   32.]]


In [62]:
print('random: {} \n'.format(np.random.random(20)))

random: [0.22860192 0.51930354 0.78849497 0.71524127 0.09517339 0.36658444
 0.36078765 0.72708317 0.71424686 0.95381407 0.82650611 0.42948846
 0.24035934 0.80425805 0.60146474 0.30950402 0.62150131 0.41410803
 0.63352055 0.55591727] 



In [64]:
print('rand:{}\n'.format(np.random.rand(3,4)))

rand:[[0.12283213 0.44050351 0.86291812 0.48679964]
 [0.35175476 0.37243831 0.69600084 0.72005387]
 [0.83881734 0.80264714 0.67599338 0.68122051]]



In [66]:
print('randint:{}\n'.format(np.random.randint(0,100,20)))

randint:[ 1 72 50 21 45 18 13 96 62 30 32 22 40 46 79  1 48  3 64 92]



In [69]:
print('permutation: {}\n'.format(np.random.permutation(np.arange(20))))

permutation: [19 10  5  1  9 18 17  2 11 16  6 12 15  7 14 13  3  4  8  0]

