In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
# rank -> 1
# length of axis -> 3
[1,2,3]

[1, 2, 3]

In [5]:
#rank -> 2
# length of the axis -> 3
[[1,2,3], [4,5,6]]

[[1, 2, 3], [4, 5, 6]]

In [6]:
# we can create an array of numpy
#thtough the array function
a = np.array([1,2,3])
b = np.array([(1,2,3), (4,5,6)])

print('a', a)
print('b', b)

a [1 2 3]
b [[1 2 3]
 [4 5 6]]


NumPy's array class is ndarray which has an alias
**numpy.array**

-> different from array.arrayin the puthon standard library

In [7]:
print(a.shape)

(3,)


In [8]:
print(b.shape)

(2, 3)


In [9]:
print(b.size)

6


In [10]:
print(a.dtype)

int64


In [11]:
print(b.dtype)

int64


In [12]:
print(b.itemsize)

8


In [13]:
print(a.data)


## 2019-07-16 

In [14]:
a = np.array([1,2,3])
print('a = ', a)

a =  [1 2 3]


In [15]:
b = np.array([(1,2,3), (4,5,6)])
print('b = ', b)

b =  [[1 2 3]
 [4 5 6]]


In [18]:
print('a ndim {}'.format(a.ndim))
print('a shape {}'.format(a.shape))
print('a size {}'.format(a.size))
print('a dtype {}'.format(a.dtype))
print('a itemsize {}'.format(a.itemsize))


a ndim 1
a shape (3,)
a size 3
a dtype int64
a itemsize 8


In [19]:
print('b ndim {}'.format(b.ndim))
print('b shape {}'.format(b.shape))
print('b size {}'.format(b.size))
print('b dtype {}'.format(b.dtype))
print('b itemsize {}'.format(b.itemsize))

b ndim 2
b shape (2, 3)
b size 6
b dtype int64
b itemsize 8


In [22]:
c = np.array([[1,2], [3,4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [23]:
c = np.array([[1,2], [3,4]], dtype=float)
c

array([[1., 2.],
       [3., 4.]])

In [25]:
a = np.zeros((2,3))
print('np.zero((2,3) = \n{}\n'.format(a))

np.zero((2,3) = 
[[0. 0. 0.]
 [0. 0. 0.]]



In [26]:
b = np.ones((2,3))
print('np.ones((2,3)) = \n{}\n'.format(b))

np.ones((2,3)) = 
[[1. 1. 1.]
 [1. 1. 1.]]



In [28]:
c = print('np.empty((2,3)) = \n{}\n'.format(a))

np.empty((2,3)) = 
[[0. 0. 0.]
 [0. 0. 0.]]



In [30]:
d = np.arange(1,2,0.3)

In [31]:
print('np.arange(1,2,0.3) = \n{}\n'.format(d))

np.arange(1,2,0.3) = 
[1.  1.3 1.6 1.9]



In [34]:
e = np.linspace(1,2,7)
print('np.linspace(1,2,7) = \n{}\n'. format(e))

np.linspace(1,2,7) = 
[1.         1.16666667 1.33333333 1.5        1.66666667 1.83333333
 2.        ]



In [36]:
f = np.random.random((2,3))
print('np.random.random((2,3)) = \n{}\n'.format(f))

np.random.random((2,3)) = 
[[0.71966965 0.48368488 0.74124921]
 [0.30739298 0.87751244 0.54039596]]

