### Shape and Operation
In addition to generating an array, after we have held some data, we may need to generate some new data structures **based on the existing array**. We can use the following functions.

* reshape
* vstack
* hstack
* hsplit
* vsplit

In [1]:
import numpy as np

In [2]:
# test data
zero_line = np.zeros((1,3))
one_column = np.ones((3,1))
print('zero_line = \n{}\n'.format(zero_line))
print('one_column = \n{}\n'.format(one_column))

zero_line = 
[[0. 0. 0.]]

one_column = 
[[1.]
 [1.]
 [1.]]



In [3]:
#test data
a = np.array([(1,2,3), (4,5,6)])
b = np.arange(11,20) #in one line
print('a = \n{}\n'.format(a))
print('b = \n{}\n'.format(b))

a = 
[[1 2 3]
 [4 5 6]]

b = 
[11 12 13 14 15 16 17 18 19]



this array **b** is a **one-dimension array** originally, and we **resize** it into a **matrix of 3 rows and 3 columns** byt the **reshape** method

In [6]:
b = b.reshape(3, -1)
print('b.reshape(3,-1) = \n{}\n'.format(b))


b.reshape(3,-1) = 
[[11 12 13]
 [14 15 16]
 [17 18 19]]



In [9]:
# why is it -1
test = np.arange(1,21)
print(test,'\n')
test1 = test.reshape(2,-1)
print(test1, '\n')
test2 = test.reshape(4,-1)
print(test2, '\n')
test3 = test.reshape(5,4)
print(test3, '\n')

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] 

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]] 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]] 



Next, we will **stack the 3 arrays vertically** through the vstack function

In [10]:
c = np.vstack((a,b, zero_line))
print(c)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [11. 12. 13.]
 [14. 15. 16.]
 [17. 18. 19.]
 [ 0.  0.  0.]]


Similary, we can also use the **hstack for the horizontal stacking**. This time we need time to **adjust the structure of the array** at first.

In [11]:
a = a.reshape(3,2)
print(a)
#have to change 

[[1 2]
 [3 4]
 [5 6]]


In [14]:
d = np.hstack((a,b,one_column)) 
print(d)

[[ 1.  2. 11. 12. 13.  1.]
 [ 3.  4. 14. 15. 16.  1.]
 [ 5.  6. 17. 18. 19.  1.]]


We split the array **d** into **three arrays in the horizontal direction**

In [16]:
e = np.hsplit(d,3)
print(e)

[array([[1., 2.],
       [3., 4.],
       [5., 6.]]), array([[11., 12.],
       [14., 15.],
       [17., 18.]]), array([[13.,  1.],
       [16.,  1.],
       [19.,  1.]])]


In [17]:
print(e[1])

[[11. 12.]
 [14. 15.]
 [17. 18.]]


In [18]:
print(e[0])

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [19]:
print(e[2])

[[13.  1.]
 [16.  1.]
 [19.  1.]]


In [21]:
f = np.hsplit(d,(1,3))
#split a after the 1st and the 3rd column
print(f)

[array([[1.],
       [3.],
       [5.]]), array([[ 2., 11.],
       [ 4., 14.],
       [ 6., 17.]]), array([[12., 13.,  1.],
       [15., 16.,  1.],
       [18., 19.,  1.]])]


In [22]:
print(f[0])

[[1.]
 [3.]
 [5.]]


In [23]:
print(f[1])

[[ 2. 11.]
 [ 4. 14.]
 [ 6. 17.]]


In [24]:
print(f[2])

[[12. 13.  1.]
 [15. 16.  1.]
 [18. 19.  1.]]


Finally, we split the array **d** in the **vertical direction**

In [25]:
g = np.vsplit(d,3)
print(g)

[array([[ 1.,  2., 11., 12., 13.,  1.]]), array([[ 3.,  4., 14., 15., 16.,  1.]]), array([[ 5.,  6., 17., 18., 19.,  1.]])]


In [26]:
print(g[0])

[[ 1.  2. 11. 12. 13.  1.]]


In [27]:
print(g[1])

[[ 3.  4. 14. 15. 16.  1.]]


In [28]:
print(g[2])

[[ 5.  6. 17. 18. 19.  1.]]
